component_depth: 1
languages:
- csharp

exclude:
- /.vscode/.*
- /Packages/.*
- /ProjectSettings/.*

- /Characters/.*
- /Invector-3rdPersonController/.*
- /Materials/.*
- /PostProcessing/.*
- /Prefabs/.*
- /ProBuilder Data/.*
- /Scenes/.*
- /Sound/.*
- /Standard Assets/.*
