component_depth: 1
languages:
- csharp

exclude:
- /.vscode/.*
- /Packages/.*
- /ProjectSettings/.*

- /Scripts/Characters/.*
- /Scripts/Invector-3rdPersonController/.*
- /Scripts/Materials/.*
- /Scripts/PostProcessing/.*
- /Scripts/Prefabs/.*
- /Scripts/ProBuilder Data/.*
- /Scripts/Scenes/.*
- /Scripts/Sound/.*
- /Scripts/Standard Assets/.*
